# -*- coding: utf-8 -*-
"""Image Watermarking Tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IQAmA_dMl9cDcECadkBNsOsxwJ96gBNn
"""

from PIL import Image, ImageDraw, ImageFont
import matplotlib.pyplot as plt

img = Image.open('sample.png')

teks = input("Input Your Custom Watermark: ")

draw = ImageDraw.Draw(img)
font = ImageFont.load_default()
text_width, text_height = draw.textsize(teks, font=font)
text_x = (img.width - text_width) // 2
text_y = (img.height - text_height) // 2
draw.text((text_x, text_y), teks, font=font, fill=(255, 255, 255, 128))

img_rgb = img.convert('RGB')

img_rgb.save('with_watermark.jpg')

fig, ax = plt.subplots(1, 2, figsize=(12, 6))
ax[0].imshow(img)
ax[0].set_title('Original Image')
ax[0].axis('off')

ax[1].imshow(img_rgb)
ax[1].set_title('Image with Watermark')
ax[1].axis('off')

plt.show()